# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8bb672c821ee7b099711e959ec6dbf67792d570559dfe77c296da77e5fff3500b8c9dbb4ad73a38a83a1813d90df9323743308e8fa9bf9fbcd4b3c1c583036b

test:
  secret_key_base: efb945d2a31225250e7a0f89cb06ea2066dcf56fed0f69c30dbe4c6f5e3d22a0056c2a874c8a4118ee4b1d1c350a5147a1a7775fe21e87984d90325ebdd0e7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
